#!/usr/bin/env bash
#prints strings indefinitely and another string when receiving a sigterm signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
